// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdataApi.Contexts;

namespace OdataApi.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20210523115112_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OdataApi.Entities.Oyun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("Puani")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("YapimciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YapimciId");

                    b.ToTable("Oyunlar");
                });

            modelBuilder.Entity("OdataApi.Entities.Yapimci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Yapimcilar");
                });

            modelBuilder.Entity("OdataApi.Entities.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklamasi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OyunId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YorumcuAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OyunId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("OdataApi.Entities.Oyun", b =>
                {
                    b.HasOne("OdataApi.Entities.Yapimci", "Yapimci")
                        .WithMany("Oyunlar")
                        .HasForeignKey("YapimciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yapimci");
                });

            modelBuilder.Entity("OdataApi.Entities.Yorum", b =>
                {
                    b.HasOne("OdataApi.Entities.Oyun", "Oyun")
                        .WithMany("Yorumlar")
                        .HasForeignKey("OyunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oyun");
                });

            modelBuilder.Entity("OdataApi.Entities.Oyun", b =>
                {
                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("OdataApi.Entities.Yapimci", b =>
                {
                    b.Navigation("Oyunlar");
                });
#pragma warning restore 612, 618
        }
    }
}
